### ISSUE TITLE
TTL or expiration for keys?

### ISSUE THREAD

**Issue by MarcoLugo** [privacysandbox/protected-auction-key-value-service#32]
Are there any plans to add a key-expiry/TTL mechanism to the key-value service? If not, is this something that could be considered? Thank you.

**Comment by peiwenhu** [comment]
Hi,

There was a similar question in https://github.com/privacysandbox/fledge-key-value-service/issues/2. The server supports direct deletion operation today so an offline job can manage TTL.

It still seems to us that managing TTL is better done outside TEE to reduce the complexity, although we are open to understanding new concerns.

Since systems outside the TEE can be customized and implemented by the server operators without reliance on our team, it is currently a low priority for us.

**Comment by MarcoLugo** [comment]
Thank you for your response. Sorry I missed that issue, it does have helpful context. We'll try to think about how we could make this work and if we have specific concerns I'll get back you. Thank you.
