### ISSUE TITLE
dependency version error(0.7.0) while building AMI

### ISSUE THREAD

**Issue by k-o-ta** [privacysandbox/protected-auction-key-value-service#7]
Hi

I tried to build AMI following the [doc](https://github.com/privacysandbox/fledge-key-value-service/blob/main/docs/deploying_on_aws.md#build-the-amazon-machine-image-ami), and got dependency version errors during build.
[This commit](https://github.com/k-o-ta/fledge-key-value-service/commit/10b373c274bc55804fc6fcd92c4e1a9b8f752341) shows versions I had to update to build AMI. I tried version 0.7.0.
I did not create a pull request because I was not sure if I could simply specify a newer version.

**Comment by peiwenhu** [comment]
Hi, thanks for letting us know.

This is a unique challenge that we begin to realize now.

We must support reproducible builds in order to conform to [our trust model](https://github.com/privacysandbox/fledge-docs/blob/main/key_value_service_trust_model.md):
> To decrypt the requests, the adtech-operated key/value service uses the private keys, which it has previously obtained from the KMS by attesting that it is running an approved version of the code in the TEE.

For that, we must ensure when people build the system the outcome is deterministic. So we must use specific dependency versions, but those dependencies may not always have those versions available as time goes on.

It's our top priority to solve this asap. For now, I think your solution to relax the version on your side is the right thing to do.

**Comment by peiwenhu** [comment]
We have released v0.8.0 which can be built now. The underlying problem as I mentioned above still looms and we are working on the fundamental fix.
